"""Machine-stable reason-code registry for governed runtime decisions."""

from __future__ import annotations

import re

RESOURCE_UNRESOLVED = "RESOURCE.UNRESOLVED"
AUTH_CREDENTIAL_MISSING = "AUTH.CREDENTIAL_MISSING"
AUTH_CREDENTIAL_INVALID = "AUTH.CREDENTIAL_INVALID"
AUTH_CREDENTIAL_EXPIRED = "AUTH.CREDENTIAL_EXPIRED"
AUTH_CREDENTIAL_NOT_YET_VALID = "AUTH.CREDENTIAL_NOT_YET_VALID"
AUTH_CREDENTIAL_REPLAYED = "AUTH.CREDENTIAL_REPLAYED"
AUTH_CREDENTIAL_REVOKED = "AUTH.CREDENTIAL_REVOKED"
AUTH_PRINCIPAL_MISMATCH = "AUTH.PRINCIPAL_MISMATCH"
AUTH_IDENTITY_INACTIVE = "AUTH.IDENTITY_INACTIVE"
AUTH_PROVIDER_FAILURE = "AUTH.PROVIDER_FAILURE"
AUTH_INTERNAL_ERROR = "AUTH.INTERNAL_ERROR"
REGISTRY_CAPABILITY_DENIED = "REGISTRY.CAPABILITY_DENIED"
REGISTRY_UNKNOWN_ROLE = "REGISTRY.UNKNOWN_ROLE"
REGISTRY_REVISION_CONFLICT = "REGISTRY.REVISION_CONFLICT"
REGISTRY_OPERATION_CONFLICT = "REGISTRY.OPERATION_CONFLICT"
REGISTRY_IDENTITY_NOT_FOUND = "REGISTRY.IDENTITY_NOT_FOUND"
REGISTRY_IDENTITY_INACTIVE = "REGISTRY.IDENTITY_INACTIVE"
REGISTRY_TAMPER_DETECTED = "REGISTRY.TAMPER_DETECTED"
RBAC_PERMISSION_DENIED = "RBAC.PERMISSION_DENIED"
GUARDRAIL_TIMEOUT = "GUARDRAIL.TIMEOUT"
GUARDRAIL_INTERNAL_ERROR = "GUARDRAIL.INTERNAL_ERROR"
RATE_LIMIT_EXCEEDED = "RATE_LIMIT.EXCEEDED"
CIRCUIT_BREAKER_OPEN = "CIRCUIT_BREAKER.OPEN"
EXECUTION_CANCELLED = "EXECUTION.CANCELLED"
EXECUTION_FAILED = "EXECUTION.FAILED"
EXECUTION_ADMISSION_WITHOUT_COMPLETION = "EXECUTION.ADMISSION_WITHOUT_COMPLETION"
EXECUTION_CLAIMED_WITHOUT_TERMINAL = "EXECUTION.CLAIMED_WITHOUT_TERMINAL"
EXECUTION_COMPLETION_WITHOUT_PROTECTED_RESULT = "EXECUTION.COMPLETION_WITHOUT_PROTECTED_RESULT"
EXECUTION_PROTECTED_RESULT_AVAILABLE = "EXECUTION.PROTECTED_RESULT_AVAILABLE"
EXECUTION_RECONCILED_DENY = "EXECUTION.RECONCILED_DENY"
DELIVERY_CANCELLED = "DELIVERY.CANCELLED"
INPUT_INVALID = "INPUT.INVALID"
OUTPUT_SCHEMA_INVALID = "OUTPUT.SCHEMA_INVALID"
PII_INPUT_REDACTED = "PII.INPUT_REDACTED"
PII_EGRESS_DENIED = "PII.EGRESS_DENIED"
SECRET_EGRESS_DENIED = "SECRET.EGRESS_DENIED"  # noqa: S105 - reason code, not a secret
FAIR_PROTECTED_FEATURE_IN_INPUT = "FAIR.PROTECTED_FEATURE_IN_INPUT"
FAIR_DI_RATIO_BELOW_THRESHOLD = "FAIR.DI_RATIO_BELOW_THRESHOLD"
FAIR_CHECK_FAILED = "FAIR.CHECK_FAILED"
MRM_MODEL_UNVALIDATED = "MRM.MODEL_UNVALIDATED"
HITL_REVIEW_BAND = "HITL.REVIEW_BAND"
HITL_APPROVAL_REQUIRED = "HITL.APPROVAL_REQUIRED"
HITL_POST_APPROVAL_REQUIRED = "HITL.POST_APPROVAL_REQUIRED"
HITL_SECOND_APPROVAL_REQUIRED = "HITL.SECOND_APPROVAL_REQUIRED"
AA_NO_REASON_CODES = "AA.NO_REASON_CODES"
AA_UNKNOWN_CODE = "AA.UNKNOWN_CODE"
AA_CODE_NOT_ATTRIBUTED = "AA.CODE_NOT_ATTRIBUTED"
AA_ATTRIBUTION_MODEL_MISMATCH = "AA.ATTRIBUTION_MODEL_MISMATCH"
AA_POLICY_REASON_UNBOUND = "AA.POLICY_REASON_UNBOUND"
AA_REVIEW_REASON_UNBOUND = "AA.REVIEW_REASON_UNBOUND"
AA_UNRESOLVED_DECLINE = "AA.UNRESOLVED_DECLINE"
AA_NO_TRUE_FACTORS = "AA.NO_TRUE_FACTORS"
AA_UNMAPPED_FEATURES = "AA.UNMAPPED_FEATURES"
AA_INVALID_ATTRIBUTION = "AA.INVALID_ATTRIBUTION"
AA_TAXONOMY_MISMATCH = "AA.TAXONOMY_MISMATCH"
AA_NOTICE_INCOMPLETE = "AA.NOTICE_INCOMPLETE"
AA_NOTICE_WINDOW_EXCEEDED = "AA.NOTICE_WINDOW_EXCEEDED"
PII_UNSAFE_DECISION_EVIDENCE = "PII.UNSAFE_DECISION_EVIDENCE"
SANDBOX_BACKEND_REQUIRED = "SANDBOX.BACKEND_REQUIRED"
SANDBOX_CONFIG_INVALID = "SANDBOX.CONFIG_INVALID"
SANDBOX_COMMAND_INVALID = "SANDBOX.COMMAND_INVALID"
SANDBOX_OBLIGATION_CONFLICT = "SANDBOX.OBLIGATION_CONFLICT"
SANDBOX_SDK_UNAVAILABLE = "SANDBOX.SDK_UNAVAILABLE"
SANDBOX_START_FAILED = "SANDBOX.START_FAILED"
SANDBOX_TIMEOUT = "SANDBOX.TIMEOUT"
SANDBOX_PROCESS_EXIT_NONZERO = "SANDBOX.PROCESS_EXIT_NONZERO"
SANDBOX_CLEANUP_FAILED = "SANDBOX.CLEANUP_FAILED"
SANDBOX_INTERNAL_ERROR = "SANDBOX.INTERNAL_ERROR"
SANDBOX_REQUIRED = "SANDBOX.REQUIRED"

RUNTIME_REASON_CODES = frozenset(
    {
        RESOURCE_UNRESOLVED,
        AUTH_CREDENTIAL_MISSING,
        AUTH_CREDENTIAL_INVALID,
        AUTH_CREDENTIAL_EXPIRED,
        AUTH_CREDENTIAL_NOT_YET_VALID,
        AUTH_CREDENTIAL_REPLAYED,
        AUTH_CREDENTIAL_REVOKED,
        AUTH_PRINCIPAL_MISMATCH,
        AUTH_IDENTITY_INACTIVE,
        AUTH_PROVIDER_FAILURE,
        AUTH_INTERNAL_ERROR,
        REGISTRY_CAPABILITY_DENIED,
        REGISTRY_UNKNOWN_ROLE,
        REGISTRY_REVISION_CONFLICT,
        REGISTRY_OPERATION_CONFLICT,
        REGISTRY_IDENTITY_NOT_FOUND,
        REGISTRY_IDENTITY_INACTIVE,
        REGISTRY_TAMPER_DETECTED,
        RBAC_PERMISSION_DENIED,
        GUARDRAIL_TIMEOUT,
        GUARDRAIL_INTERNAL_ERROR,
        RATE_LIMIT_EXCEEDED,
        CIRCUIT_BREAKER_OPEN,
        EXECUTION_CANCELLED,
        EXECUTION_FAILED,
        EXECUTION_ADMISSION_WITHOUT_COMPLETION,
        EXECUTION_CLAIMED_WITHOUT_TERMINAL,
        EXECUTION_COMPLETION_WITHOUT_PROTECTED_RESULT,
        EXECUTION_PROTECTED_RESULT_AVAILABLE,
        EXECUTION_RECONCILED_DENY,
        DELIVERY_CANCELLED,
        INPUT_INVALID,
        OUTPUT_SCHEMA_INVALID,
        PII_INPUT_REDACTED,
        PII_EGRESS_DENIED,
        SECRET_EGRESS_DENIED,
        FAIR_PROTECTED_FEATURE_IN_INPUT,
        FAIR_DI_RATIO_BELOW_THRESHOLD,
        FAIR_CHECK_FAILED,
        MRM_MODEL_UNVALIDATED,
        HITL_REVIEW_BAND,
        HITL_APPROVAL_REQUIRED,
        HITL_POST_APPROVAL_REQUIRED,
        HITL_SECOND_APPROVAL_REQUIRED,
        AA_NO_REASON_CODES,
        AA_UNKNOWN_CODE,
        AA_CODE_NOT_ATTRIBUTED,
        AA_ATTRIBUTION_MODEL_MISMATCH,
        AA_POLICY_REASON_UNBOUND,
        AA_REVIEW_REASON_UNBOUND,
        AA_UNRESOLVED_DECLINE,
        AA_NO_TRUE_FACTORS,
        AA_UNMAPPED_FEATURES,
        AA_INVALID_ATTRIBUTION,
        AA_TAXONOMY_MISMATCH,
        AA_NOTICE_INCOMPLETE,
        AA_NOTICE_WINDOW_EXCEEDED,
        PII_UNSAFE_DECISION_EVIDENCE,
        SANDBOX_BACKEND_REQUIRED,
        SANDBOX_CONFIG_INVALID,
        SANDBOX_COMMAND_INVALID,
        SANDBOX_OBLIGATION_CONFLICT,
        SANDBOX_SDK_UNAVAILABLE,
        SANDBOX_START_FAILED,
        SANDBOX_TIMEOUT,
        SANDBOX_PROCESS_EXIT_NONZERO,
        SANDBOX_CLEANUP_FAILED,
        SANDBOX_INTERNAL_ERROR,
        SANDBOX_REQUIRED,
    }
)

_RESERVED_RUNTIME_NAMESPACES = frozenset(code.partition(".")[0] for code in RUNTIME_REASON_CODES)

# Policy IDs use PolicyRule's stable uppercase identifier contract. Custom
# guardrails may use their own dotted uppercase namespace, but cannot impersonate
# an unregistered built-in runtime code.
_POLICY_REASON_CODE = re.compile(r"^[A-Z0-9][A-Z0-9._-]{0,63}$")
_EXTENSION_REASON_CODE = re.compile(r"^[A-Z][A-Z0-9_]*(?:\.[A-Z][A-Z0-9_]*)+$")


def is_valid_reason_code(code: str) -> bool:
    """Return whether ``code`` is registered or a valid policy/extension ID."""

    if code in RUNTIME_REASON_CODES:
        return True
    if code.partition(".")[0] in _RESERVED_RUNTIME_NAMESPACES:
        return False
    if "-" in code and _POLICY_REASON_CODE.fullmatch(code):
        return True
    return bool(_EXTENSION_REASON_CODE.fullmatch(code))
